##########################################################
#                   ORIGINAL AUTHOR                      #
#                     LEANDROSSJ                         #
#                                                        #
#                  SKIDDED BY ANDREW                     #
#                 MAKER OF VERSION V2                    #
#                                                        #
#                 discord.helydev.com                    #
##########################################################

commands: # If you want the command to be enabled, it needs to be true, if you want it disabled it needs to be false.
  MediaOwnerCommand: true
  PartnerCommand: true
  YoutuberCommand: true
  CopyInventoryCommand: true
  SkullCommand: true
  EnchantCommand: true
  BottleCommand: true
  DiscordCommand: true
  TelegramCommand: true
  FamousCommand: true
  NightCommand: true
  SetMOTDCommand: true
  ItemIDCommand: true
  DayCommand: true
  WebsiteCommand: true
  TeamspeakCommand: true
  StoreCommand: true
  FightCommand: true
  EndPlayersCommand: true
  NearCommand: true
  ClearInventoryCommand: true
  InvseeCommand: true
  HubCommand: true
  FeedCommand: true
  CraftCommand: true
  RenameCommand: true
  KillCommand: true
  EnderChestCommand: true
  LoreCommand: true
  ListCommand: true
  SpawnerCommand: true
  SpawnCommand: true # This will also enable/disable the /setspawn command.
  PlaytimeCommand: true
  GameModeCommand: true
  BroadcastCommand: true
  BroadcastRawCommand: true
  SetColorCommand: true
  TeleportCommand: true
  TeleportPositionCommand: true
  HatCommand: true
  HealCommand: true
  TeleportHereCommand: true
  ServerStatusCommand: true
  PokeCommand: true
  HiderCommand: true
  RepairCommand: true
  HelpCommand: true
  TopCommand: true
  TpAllCommand: true
  WorldCommand: true

#####################################################################################

settings:
  server: # Server Events
    donate-url: "store.yourserver.com"
    perks-system: true # This will enable Speed, Fire Res, Invisibility Commands.
    pearl-glitch: true # Do you want the plugin to stop pearl glitching?
    void-teleport-fix: true # Do you want the plugin to teleport a player to spawn after they fall in the void?
    kill-tracker: true # Do you want to enable kill tracker?
    stat-trak: true # Do you want to enable StatTrak? (This will also enable/disable the pickaxe stats, along with kill stats on swords!)
    whitelist-message: "&cSorry, this server is currently in maintenance."
  custom-enchants:
    enabled: true # Do you want to have it enabled?

    Speed-Lore: "&b&nSpeed II"
    Fire-Resistance-Lore: "&c&nFire Resistance I"
  limiters:
    potion-limiter: true # Do you want to enable this system?
    enchant-limiter: true # Do you want to enable this system?
  pvp: # PvP Events
    hit-detection: 21 # 21 is the default number.
    splash-potion-velocity: 2.0 # 2.0 is the default number.
  elevators:
    enabled: true
    invalid: "&cSorry, it needs to be either UP or DOWN."

    used-sound: true # Do you want to enable the sound for when you use the sign?
    sound_name: CLICK # The name of the sound when you use the sign.

#####################################################################################

hub-command:
  hub-server: "Hub" # This is the BungeeCord name of your hub.

#####################################################################################

potion-refill-sign:
  enabled: true

  sound: true
  sound-name: "CHEST_OPEN"

  title: "Potion Refill:" # The title of the menu.

  line-1: ""
  line-2: "&b&lFree"
  line-3: "&b&lPotions"
  line-4: ""

  permission-create: "core.refill.create" # The permission required to create the sign.

#####################################################################################

join-sound:
  enabled: true

#####################################################################################

enderchest:
  enabled: true

  size: 9 # The size of the player vault, it can be "9, 18, 27, 36, 45, 54".

#####################################################################################

spawn: # DO NOT EDIT. THIS WILL BREAK YOUR CORE. YOU CAN CHANGE THESE COORDINATES VIA THE /SETSPAWN COMMAND INGAME!
  world: world
  x: 0.538049846829157
  y: 69.0
  z: 0.6617853658512408
  yaw: 0.78689575
  pitch: 11.715501

#####################################################################################

beacon-rename:
  enabled: true # Do you want to enable this system?

  scrambling: "&9Random Name... &7%random%"
  random: "&6Your item has been renamed to: &f%name%"
  cooldown-active: "&cYou have to wait %time% seconds."
  need-sword: "&cYou must have a sword in your hand."
  name-list:
    - "&4Hely Development"
    - "&c&lWE HATE LAUTI"
    - "&d&lLeandroSSJ <3"
    - "&7&nGod Player"

#####################################################################################

killstreaks:
  enabled: true # Do you want to enable this system?
  broadcast-message: "&b&l[!] %player% &fhas reached &d%killstreak% kills &fand has recieved &5&l%item%&f."
  items: # These are the items that you want the player to be given when they reach certain amounts of kills!
    KillReward:
      name: "KillReward"
      kills: 10
      commands:
        - "crate givekey %player% Reward 15"

#####################################################################################

rename-command:
  warn: true # Do you wany the console to warn players who use a blocked rename word?
  swords-only: true # Do you want to make it so you can ONLY rename swords? NOTE: This stops dupe glitches. If you would like a player to bypass this, you can give them core.command.rename.bypass.
  warn-command: "warn %player% Misuse of /rename" # The command that is executed by console when someone uses a blocked word in /rename.
  play-sound: true # Do you want to play a sound when someone uses a blocked name?
  sound-name: "CAT_MEOW" # The name of the sound.

  blocked-names:
    - "nigger"
    - "nigga"
    - "retard"
    - "faggot"

#####################################################################################
