##########################################################
#                   ORIGINAL AUTHOR                      #
#                     LEANDROSSJ                         #
#                                                        #
#                  SKIDDED BY ANDREW                     #
#                 MAKER OF VERSION V2                    #
#                                                        #
#                 discord.helydev.com                    #
##########################################################

commands: # If you want the command to be enabled, it needs to be true, if you want it disabled it needs to be false.
  MediaOwnerCommand: true
  PartnerCommand: true
  YoutuberCommand: true
  CopyInventoryCommand: true
  SkullCommand: true
  OresCommand: true
  EnchantCommand: true
  BottleCommand: true
  DiscordCommand: true
  TelegramCommand: true
  FamousCommand: true
  NightCommand: true
  SetMOTDCommand: true
  ClearLagCommand: true
  ItemIDCommand: true
  DayCommand: true
  WebsiteCommand: true
  TeamspeakCommand: true
  StoreCommand: true
  FightCommand: true
  EndPlayersCommand: true
  NearCommand: true
  ClearInventoryCommand: true
  InvseeCommand: true
  HubCommand: true
  GiveCommand: true
  FeedCommand: true
  CraftCommand: true
  RenameCommand: true
  KillCommand: true
  EnderChestCommand: true
  LoreCommand: true
  ListCommand: true
  SpawnerCommand: true
  SpawnCommand: true # This will also enable/disable the /setspawn command.
  PlaytimeCommand: true
  GameModeCommand: true
  BroadcastCommand: true
  BroadcastRawCommand: true
  SetColorCommand: true
  TeleportCommand: true
  TeleportPositionCommand: true
  HatCommand: true
  HealCommand: true
  TeleportHereCommand: true
  ServerStatusCommand: true
  PokeCommand: true
  ReportCommand: true
  HelpOpCommand: true
  HiderCommand: true
  RepairCommand: true
  HelpCommand: true
  TopCommand: true
  TpAllCommand: true
  WorldCommand: true

#####################################################################################

settings:
  server: # Server Events
    timezone: "EST" # What timezone is your server in?
    voucher-system: true # Do you want to enable the voucher system?
    anti-dropdown: true # Do you want to disable people from placing doors below a certain Y level?
    ghost-block-fixer: true # Do you want to fix people from creating Ghost Blocks?
    perks-system: true # This will enable Speed, Fire Res, Invisibility Commands.
    pearl-glitch: true # Do you want the plugin to stop pearl glitching?
    kill-tracker: true # Do you want to enable kill tracker?
    stat-trak: true # Do you want to enable StatTrak? (This will also enable/disable the pickaxe stats, along with kill stats on swords!)
    whitelist-message: "&cSorry, this server is currently in maintenance."
  enderpearls:
    refund-command: 'timer set ENDERPEARL %player% 0'
  airdrops:
    zone-size: 800 # The size (in blocks), of the area (from 0,0) you want air-drops to spawn.
  limiters:
    potion-limiter: true # Do you want to enable this system?
    enchant-limiter: true # Do you want to enable this system?
  pvp: # PvP Events
    hit-detection: 21 # 21 is the default number.
    splash-potion-velocity: 2.0 # 2.0 is the default number.
  elevators:
    enabled: true # This will enable elevator signs.
    title: "&9[Elevator]"
    not-found: true # This will use the other elevator sign system.
    messages:
      invalid-usage: "&cPlease either use 'Up' or 'Down'!"
      cannot-find: "&cWe cannot find a sign to teleport you to."
      blocked: "&cSorry, the sign you are trying to use is currently blocked by a block."
  mob-stack:
    enabled: true # Do you want to enable the mob stacker?
    entity: # This is the list of entities you would like to be stacked.
      - "ZOMBIE"
      - "SKELETON"
      - "SPIDER"
      - "CAVE_SPIDER"
      - "COW"
      - "PIG"
      - "SHEEP"
      - "CHICKEN"
      - "HORSE"
      - "BLAZE"

#####################################################################################

hub-command:
  hub-server: "Hub" # This is the BungeeCord name of your hub.

#####################################################################################

join-sound:
  enabled: true

#####################################################################################

enderchest:
  enabled: true

  size: 9 # The size of the player vault, it can be "9, 18, 27, 36, 45, 54".

#####################################################################################

spawn: # DO NOT EDIT. THIS WILL BREAK YOUR CORE. YOU CAN CHANGE THESE COORDINATES VIA THE /SETSPAWN COMMAND INGAME!
  world: world
  x: 0.538049846829157
  y: 69.0
  z: 0.6617853658512408
  yaw: 0.78689575
  pitch: 11.715501

#####################################################################################

killstreaks:
  enabled: true # Do you want to enable this system?
  broadcast-message: "&b&l[!] %player% &fhas reached &d%killstreak% kills &fand has recieved &5&l%item%&f."
  items: # These are the items that you want the player to be given when they reach certain amounts of kills!
    KillReward:
      name: "KillReward"
      kills: 10
      commands:
        - "crate givekey %player% Reward 15"

#####################################################################################

rename-command:
  warn: true # Do you wany the console to warn players who use a blocked rename word?
  swords-only: true # Do you want to make it so you can ONLY rename swords? NOTE: This stops dupe glitches. If you would like a player to bypass this, you can give them core.command.rename.bypass.
  warn-command: "warn %player% Misuse of /rename" # The command that is executed by console when someone uses a blocked word in /rename.
  play-sound: true # Do you want to play a sound when someone uses a blocked name?
  sound-name: "CAT_MEOW" # The name of the sound.

  blocked-names:
    - "nigger"
    - "nigga"
    - "retard"
    - "faggot"

#####################################################################################

clear-lag:
  enabled: true # Do you want to enable this system?
  message: "&a&l[!] &a&n%total% entities&a has just been removed."

#####################################################################################
